spring.datasource.url: jdbc:postgres://milangupta95:6jgMMMDYD55UpdcXvX0xuqepHBfUSkFN@dpg-cjb6kn1itvpc73f8frig-a/todo_aydw
spring.datasource.username: milangupta95
spring.datasource.password: 6jgMMMDYD55UpdcXvX0xuqepHBfUSkFN

